"""empty message

Revision ID: 84136bc73ed9
Revises: 19e10e86ee7c
Create Date: 2026-02-07 03:58:08.474889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84136bc73ed9'
down_revision = '19e10e86ee7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rifa_id', sa.Integer(), nullable=False),
    sa.Column('nombre_comprador', sa.String(length=100), nullable=False),
    sa.Column('email_comprador', sa.String(length=120), nullable=False),
    sa.Column('telefono_comprador', sa.String(length=20), nullable=True),
    sa.Column('tickets', sa.String(length=500), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_pago', sa.String(length=50), nullable=True),
    sa.Column('comprobante_url', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['rifa_id'], ['rifa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    # ### end Alembic commands ###
