"""empty message

Revision ID: 86b95b50c795
Revises: 84136bc73ed9
Create Date: 2026-02-07 04:22:59.990349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b95b50c795'
down_revision = '84136bc73ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rifa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre_comprador', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email_comprador', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('telefono_comprador', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tickets', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('monto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fecha_pago', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('comprobante_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rifa_id'], ['rifa.id'], name=op.f('pago_rifa_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pago_pkey'))
    )
    # ### end Alembic commands ###
