"""empty message

Revision ID: d17085b2759b
Revises: 
Create Date: 2026-02-07 02:12:16.907813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17085b2759b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rifa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('cantidad_tickets', sa.Integer(), nullable=False),
    sa.Column('precio_ticket', sa.Float(), nullable=False),
    sa.Column('loteria', sa.String(length=50), nullable=False),
    sa.Column('fecha_sorteo', sa.String(length=50), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('metodo_pagos', sa.String(length=100), nullable=True),
    sa.Column('titular_zelle', sa.String(length=100), nullable=True),
    sa.Column('contacto_zelle', sa.String(length=100), nullable=True),
    sa.Column('titular_transferencia', sa.String(length=100), nullable=True),
    sa.Column('numero_ruta', sa.String(length=50), nullable=True),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rifa_id', sa.Integer(), nullable=False),
    sa.Column('numero_ticket', sa.String(length=20), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rifa_id'], ['rifa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comprador_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('nombre_comprador', sa.String(length=100), nullable=False),
    sa.Column('email_comprador', sa.String(length=120), nullable=False),
    sa.Column('telefono_comprador', sa.String(length=20), nullable=True),
    sa.Column('comprobante_pago', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comprador_ticket')
    op.drop_table('ticket')
    op.drop_table('rifa')
    op.drop_table('user')
    # ### end Alembic commands ###
